experiment_name: edsr_x4_div2k
device: cuda:0  # 或 cpu
model:
  name: EDSR
  params:
    scale: 4
    ngf: 64
    n_resblocks: 16
data:
  dataset_name: DIV2K
  params:
    root: ./datasets/DIV2K
    scale: 4
    crop_size: 64  # LR图像裁剪大小（HR为64*4=256）
train:
  batch_size: 16
  num_workers: 4
  max_epochs: 100
optimizer:
  name: Adam
  params:
    lr: 2e-4
loss: l1  # 损失函数名称
val:
  interval: 1  # 每1个epoch验证一次
log:
  dir: ./logs
  use_tensorboard: True
checkpoint:
  save_dir: ./checkpoints